### ISSUE TITLE
[Feature Request] Publisher + Edition

### ISSUE THREAD

**Issue by Hobokens** [evoWeb/sf_books#1]
Hi, 
thanks for the extension. 
It would be great to have two more fields for the  publisher (publishing company) and the edition. 
Regards
Hobokens

**Comment by garbast** [comment]
It's possible to extend both the database table and the model with the help of https://github.com/evoweb/extender Please have a look and understand that extender helps to achive. It is exactly what you need.

For this reason i turn down the request.
