### ISSUE TITLE
Template path flexform is not respected

### ISSUE THREAD

**Issue by mahrezo** [evoWeb/sf_books#10]
I want to use a custom template for the plugin `sfbooks_book` but the HTML file is not respected on FE. it always loads the default template : `Resources/Private/Templates/Book/List.html`.

I checked the table `tt_content ` for this content and it give this :

**pi_flexform :** 

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3FlexForms>
    <data>
        <sheet index="sDEF">
            <language index="lDEF">
                <field index="settings.limit">
                    <value index="vDEF">30</value>
                </field>
                <field index="settings.category">
                    <value index="vDEF">27407</value>
                </field>
                <field index="view.templateRootPaths.200">
                    <value index="vDEF">t3://file?uid=88205</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```

**TYPO3 :** 9.5.31
**sf_books :** 6.1.1

**Comment by garbast** [comment]
After analyzing the problem i found, that the flexform does not select for the right view.... config. I need to work on a fix for that.

Edit: after some back and forth i reconsider the config right, but it shoud to select a temlate root folder. In this folder there need to be folders for the controller and in each folder the corresponding templates should reside. The rootfolder is not limited to only one  plugin but is usable for multiple outputs. E.G.

rootfolder > Book > List.html
rootfolder > Author > List.html

For this to work i change the selection from file to folder. As this never worked as intended, this is not a breaking change but a bugfix,
