### ISSUE TITLE
SF-books does not comply with typo3 v12

### ISSUE THREAD

**Issue by karelkuijpers** [evoWeb/sf_books#11]
I tried to install SF-Books 8.0.0 on typo3 v 12 and Ubuntu 22.4. Typo3 v12 works with php 8.1. Sf_books requires typo3/testing-framework[dev-main] which requires php 8.2. So I couldn't install it with composer. SF-Books should use typo3/testing-framework[8.2.0] which requires php 8.1.

**Comment by evoWeb** [comment]
Try using dev-develop as with that the testing-framework is only installed as require-dev.

**Comment by garbast** [comment]
For TYPO3 12.x please use branch 8.x from now on.
