### ISSUE TITLE
The books of an autort not shown

### ISSUE THREAD

**Issue by karelkuijpers** [evoWeb/sf_books#12]
The template ../Author/Show.html tries to show the corresponding books of the author. But they are never supplied within the view.

**Comment by garbast** [comment]
Books are fetched from the Author model via {author.books}. By this the view does not need to get the books assigned.

**Comment by karelkuijpers** [comment]
The problem is that author.books is empty. Apparently extbase does' nt
fetch them. (Lazy?) In the backend everything works fine.

Een hartelijke groet
Karel Kuijpers

Op di 10 sep. 2024 17:30 schreef Sebastian Fischer ***@***.***

**Comment by karelkuijpers** [comment]
Dear Sebastiaan,
Here is an example.
In backend all books of author Heitzmann are shown::
[image: image.png]

In frontend

Select author Heitzmann:
[image: image.png]

Open it:
[image: image.png]

So you see no books of this author are shown.

I hope you can reopen the issue en correct your extension.


_________________________________

Karel Kuijpers

Valenberg 53

2716 LR Zoetermeer

Mobiel: 06 36545057


Op di 10 sep 2024 om 18:48 schreef Karel Kuijpers ***@***.***>:

**Comment by garbast** [comment]
I just released version 8.1.2 which is compatible with TYPO3 12.4. Maybe this solves your problem with the author view not showing the books too.
