### ISSUE TITLE
Adding to TYPO3 translation server.

### ISSUE THREAD

**Issue by ahmadkhoei** [evoWeb/sf_books#2]
Hello, 
Excuse me for writing here. I couldn't find your contact info elsewhere. Would you please add this extension to Translation server of Typo3 (http://translation.typo3.org/) in the related forge page (https://forge.typo3.org/projects/team-translation)? We have to translate it there. 

Kind Regards

**Comment by garbast** [comment]
https://forge.typo3.org/issues/87132 its requested.
