### ISSUE TITLE
The argument "each" was registered with type "array", but is of type "string" in view helper "TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper".

### ISSUE THREAD

**Issue by mahrezo** [evoWeb/sf_books#3]
I'm using TYPO3 9.5.3 and the sf_books extension to manage books.

I get this error on the singleView (detail) :

`The argument "each" was registered with type "array", but is of type "string" in view helper "TYPO3Fluid\Fluid\ViewHelpers\ForViewHelper".`

I used this template for SingleView : 
[https://github.com/evoWeb/sf_books/blob/develop/Resources/Private/Templates/Book/Show.html](url)

**Comment by garbast** [comment]
As you can see in https://github.com/evoWeb/sf_books/blob/develop/Classes/Domain/Model/Book.php is every property (author, cover, extras) that is used in each of type ObjectStorage.

If you upgraded lately via composer you need to clear cache AND use db compare in the install tool.

**Comment by mahrezo** [comment]
Thank you, the problem has been resolved and the cover is displayed

I upgraded to v5.2.2 and Run database compare and clear cache
