### ISSUE TITLE
not needed string concat on Environment::getPublicPath() condition

### ISSUE THREAD

**Issue by eliasfernandez** [evoWeb/sf_books#5]
Seems that the string concat is not needed to detect if the public path is avaialble 

https://github.com/evoWeb/sf_books/blob/b803b704301a1dc305eb9a8daa44fe9a9eb73bbd/Classes/Updates/ImageToFileReferenceUpdate.php#L334

**Comment by garbast** [comment]
Changed in the file. Will be part of the next release

**Comment by eliasfernandez** [comment]
Thanks¡
