### ISSUE TITLE
TYPO3 10 LTS How to specify which plugin book, category, series or search should be used in the Url?

### ISSUE THREAD

**Issue by helmut-winkelbach** [evoWeb/sf_books#8]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1280825466: There is more than one plugin that can handle this request (Extension: "SfBooks", Controller: "Book", action: "show"). Please specify "pluginName" argument | TYPO3\CMS\Extbase\Exception thrown in file /kunden/174878_70794/rp-hosting/5712/6712/typo3cms/typo3_src-10.4.1/typo3/sysext/extbase/Classes/Service/ExtensionService.php in line 117. Requested URL: https://www.erfurt-bahai.de/bibliothek/buecher.html?

tx_sfbooks_category%%5Baction%%5D=show&tx_sfbooks_category%%5Bbook%%5D=28&tx_sfbooks_category%%5Bcontroller%%5D=Book&cHash=de87e54220bd2d39147cb7c7e15d0ec3
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1280825466: There is more than one plugin that can handle this request (Extension: "SfBooks", Controller: "Book", action: "show"). Please specify "pluginName" argument | TYPO3\CMS\Extbase\Exception thrown in file /kunden/174878_70794/rp-hosting/5712/6712/typo3cms/typo3_src-10.4.1/typo3/sysext/extbase/Classes/Service/ExtensionService.php in line 117. Requested URL: https://www.erfurt-bahai.de/bibliothek/buecher.html?cHash=f5f9084e73de8652d92ab08702a9969a&tx_sfbooks_category%%5Baction%%5D=show&tx_sfbooks_category%%5Bbook%%5D=1&tx_sfbooks_category%%5Bcontroller%%5D=Book

**Comment by evoWeb** [comment]
The error does not happen on your example. Please reopen the issue with a link that shows the error.
